#ifndef ARKA_CONF_SENTRY
#define ARKA_CONF_SENTRY

/* PLEASE, DON'T TUCH IT */
#define BLOCK_SIZE  3
#define BLOCK_COLS  4
#define AREA_WIDTH  (BLOCK_SIZE * BLOCK_COLS)
#define BLOCK_ROWS  3
#define PADDLE_LEN  4

#endif